name: ocean10
recipe: 'drupal8'
config:
  php: '8.1'
  via: 'nginx'
  webroot: './web'
  xdebug: true
  config:
    php: lando.php.ini
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://ocean10.lndo.site"
  pma:
    type: phpmyadmin
