features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
contact_title: ''
contact_address: ''
contact_address_2: ''
contact_city: ''
contact_state: ''
contact_zip_code: ''
contact_telephone: ''
contact_map_url: ''
cas_login: '1'
title_one_url: ''
title_two_url: ''
hide_breadcrumb: 0
super_footer: 1
footer_01_size: '3'
footer_02_size: '3'
footer_03_size: '3'
footer_04_size: '3'
customize_css: ''
